<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

namespace App\GPBMetadata;

class Calculator
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa9010a1063616c63756c61746f722e70726f746f1203617070221b0a0353756d12090a016118012001280512090a016218022001280522180a06526573756c74120e0a06726573756c74180120012805322c0a0a43616c63756c61746f72121e0a0353756d12082e6170702e53756d1a0b2e6170702e526573756c7422004223ca020e4170705c43616c63756c61746f72e2020f4170705c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

